services:
  db:
    image: mysql:8
    container_name: shop_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shoponline
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: ./backend
    container_name: shop_api
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: shoponline
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./frontend
    container_name: shop_web
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  db_data:
